name: p312
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
  - esri
dependencies:
  - _libavif_api=1.2.1
  - _openmp_mutex=4.5
  - aom=3.9.1
  - asttokens=3.0.0
  - blosc=1.21.6
  - branca=0.8.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.1
  - cpython=3.12.9
  - cycler=0.12.1
  - dav1d=1.2.1
  - debugpy=1.8.13
  - decorator=5.2.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - folium=0.19.5
  - fonttools=4.56.0
  - freetype=2.13.3
  - freexl=2.0.0
  - geopandas=1.0.1
  - geopandas-base=1.0.1
  - geos=3.13.1
  - geotiff=1.7.4
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - idna=3.10
  - importlib-metadata=8.6.1
  - intel-openmp=2024.2.1
  - ipykernel=6.29.5
  - ipython=9.0.2
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.4.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libarchive=3.7.7
  - libavif16=1.2.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.12.1
  - libde265=1.0.15
  - libdeflate=1.23
  - libexpat=2.6.4
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgdal-core=3.10.2
  - libgomp=14.2.0
  - libheif=1.19.7
  - libhwloc=2.11.2
  - libiconv=1.18
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblzma=5.6.4
  - libpng=1.6.47
  - librttopo=1.1.0
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libwebp-base=1.5.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.13.7
  - libzlib=1.3.1
  - llvmlite=0.44.0
  - lz4-c=1.10.0
  - lzo=2.10
  - mapclassify=2.8.1
  - markupsafe=3.0.2
  - matplotlib-base=3.10.1
  - matplotlib-inline=0.1.7
  - minizip=4.0.7
  - mkl=2024.2.2
  - munkres=1.1.4
  - narwhals=1.33.0
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - numba=0.61.0
  - numpy=2.1.3
  - openjpeg=2.5.3
  - openssl=3.4.1
  - packaging=24.2
  - pandas=2.2.3
  - parso=0.8.4
  - patsy=1.0.1
  - pcre2=10.44
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.0.1
  - platformdirs=4.3.7
  - plotly=6.0.1
  - proj=9.6.0
  - prompt-toolkit=3.0.50
  - psutil=7.0.0
  - pthread-stubs=0.4
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.1
  - pyogrio=0.10.0
  - pyparsing=3.2.3
  - pyproj=3.7.1
  - pysocks=1.7.1
  - python=3.12.9
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytz=2024.1
  - pywin32=307
  - pyzmq=26.3.0
  - qhull=2020.2
  - rav1e=0.6.6
  - requests=2.32.3
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=75.8.2
  - shapely=2.0.7
  - six=1.17.0
  - snappy=1.2.1
  - sqlite=3.49.1
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - svt-av1=3.0.1
  - tabulate=0.9.0
  - tbb=2021.13.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tornado=6.4.2
  - traitlets=5.14.3
  - tslearn=0.6.3
  - typing_extensions=4.13.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - unicodedata2=16.0.0
  - uriparser=0.9.8
  - urllib3=2.3.0
  - vc=14.3
  - vc14_runtime=14.42.34438
  - vs2015_runtime=14.42.34438
  - wcwidth=0.2.13
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - x265=3.5
  - xerces-c=3.2.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xyzservices=2025.1.0
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - st-dbscan==0.2.3
